### ISSUE TITLE
Optimize web load

### ISSUE THREAD

**Issue by condef5** [condef5/freecodecamp-scraping#2]
The application takes a long time to load for scraping, some optimization in this part of the code would be great:

```
app.get('/data', async (req, res, next) => {
...
}
```

**Comment by ghost** [comment]
I will have a look.

**Comment by condef5** [comment]
Cool, if you have any questions, you let me know, and if you can return the images of each profile it would be great.

**Comment by ghost** [comment]
@condef5 do you strictly have to use puppeteer, as waiting for all tabs to complete loading takes about 17 seconds. I stripped a bit of time by keeping chromium running instead of reopening it on each call to ``/data``, but one could use their XHR endpoint ``https://www.freecodecamp.org/api/users/get-public-profile?username=${username}``to get all the information needed and save the CPU, memory and network transfer of running a headless browser. 

Edit: Also, returning images aren't a problem.

**Comment by condef5** [comment]
Of course it could be an option (puppeteer is not necessary).

**Comment by ghost** [comment]
@condef5 I've just updated the code to use fetch instead of puppeteer and the response time is down to 1.5s from an initial 18s, I'll open a PR shortly.
